spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/libms?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

server:
  port: 8080

jwt:
  secret: "change-this-to-a-very-long-random-secret-please"
  issuer: "libms"
  expire-minutes: 120

logging:
  level.org.springframework.security: INFO
